### PR TITLE
Disable ghc::framework header/cmake file installation

### PR DESCRIPTION
**Pull request by guoyunhe**
Fix #825

### CODE REVIEW

**Comment by Zer0xFF** [comment]
as per commit, https://github.com/gulrak/filesystem/commit/7301cd1105d363d888ddcd1c7616e57d978b71fb#diff-af3b638bc2a3e6c650974192a53c7291R14 ghc install is disabled when built as part of another project, so this won't be needed, instead, a PR to update ghc to latest should do the trick.

**Comment by guoyunhe** [comment]
Then we can close this.

**Comment by Zer0xFF** [comment]
@guoyunhe would you open an PR for this in `Dependencies`, or do you want me to do it?

**Comment by guoyunhe** [comment]
@Zer0xFF maybe you can do it. I am not familiar with git sub modules.

**Pull request closed without merging**
