### PR TITLE
Update UrlEncode()

### PR DESCRIPTION
**Pull request by Zer0xFF**

### CODE REVIEW

**Comment by jpd002** [comment]
Doesn't this serve the same purpose as [UrlEncode](https://github.com/jpd002/Play--Framework/blob/master/src/http/HttpClient.cpp#L6)? Feel free to update that function if that's the case.

**Comment by Zer0xFF** [comment]
oh, I've completely missed that, quickly looking at it, it seems to be what I need, Thanks

**Comment by Zer0xFF** [comment]
alright, that function seems to work correct par 1 change, ill label it as WIP, to test further tonight, as i have to leave the house now.

**Comment by Zer0xFF** [comment]
ok, it seems this is the only change needed.

howeverm a quick comment, according to the wiki page https://en.wikipedia.org/wiki/Percent-encoding section 2.3, wouldn't it be better to explicitly select the ones that don't need encoding, and encode everything else instead?

**Comment by jpd002** [comment]
Yes, the approach you used in your `PercentEncode` function that you initially built makes more sense than what I did. You can replace my implementation with yours (while keeping the `UrlEncode` function name).

**Comment by jpd002** [comment]
Thanks!!

**Pull request merged**
