### PR TITLE
Support GCC on Unix [WIP]

### PR DESCRIPTION
**Pull request by Alloyed**
Tested on an Arch Linux machine, GCC 5.2.0. The CMakeLists was modified
to be more portable, and a few source code errors were fixed.

Update: This doesn't seem to link cleanly. I'll update as soon as I've gotten the full system working

### CODE REVIEW

**Comment by jpd002** [comment]
Thanks for the PR and sorry for the slow response. 

Sorry, that CMakeLists is quite a mess, I've only made it so that it can build on my specific setup. I'll get myself a Linux setup so I can try your changes.

**Comment by Alloyed** [comment]
No worries, even as-is the CMakeLists.txt gave me enough hints to start porting the rest of the project.
I have an extra patch to define the the app/config dirs on XDG respecting systems: would you rather I push it here or spin it into its own PR?

**Comment by jpd002** [comment]
@Alloyed Thanks! I think the config dir stuff should be added to a different PR.

**Comment by jpd002** [comment]
Ok, finally got around merging this, but I had to disable building of PosixFileStream for now since Linux, FreeBSD and Android do not seem to have a common way of handling large files. I'll have to find a better way to handle them later on.

**Pull request merged**
